import assert from "node:assert/strict";
import test from "node:test";

const OWNER_NODE = "0x787192fc5378cc32aa956ddfdedbf26b24e8d78e40109add0eea2c1a012c3dec";
const AGENT_NODE = "0xdd6fbcc964c82b43fdd8e204adf97622963b719d8fe12ebf48264a4677a4dd55";
const AGENT_ADDRESS = "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
const EXECUTOR_ADDRESS = "0x3B42d507E1B13eE164cAb0FbA4EA66f8a1B653f1";
const TASK_LOG_ADDRESS = "0x3AB718580b476D64fdD3CE6a9Ab63491B15767d9";
const UNISWAP_ROUTER = "0x1111111111111111111111111111111111111111";
const UNISWAP_SELECTOR = "0x12aa3caf";

function policyInput(overrides = {}) {
  return {
    agentAddress: AGENT_ADDRESS,
    agentName: "assistant.agentpassports.eth",
    agentNode: AGENT_NODE,
    capabilities: ["task-log", "sponsored-execution"],
    chainId: 11155111n,
    executorAddress: EXECUTOR_ADDRESS,
    expiresAt: 1790000000n,
    maxGasReimbursementWei: 200000000000000n,
    maxValueWei: 0n,
    ownerName: "agentpassports.eth",
    ownerNode: OWNER_NODE,
    target: TASK_LOG_ADDRESS,
    ...overrides,
  };
}

test("policy metadata document is generated by the app with active ENS status by default", async () => {
  const { buildAgentPolicyDocument } = await import("../apps/web/lib/policyMetadata.ts");

  const result = buildAgentPolicyDocument(policyInput());

  assert.equal(result.document.version, 1);
  assert.equal(result.document.agent.name, "assistant.agentpassports.eth");
  assert.equal(result.document.agent.status, "active");
  assert.equal(result.document.policy.target, TASK_LOG_ADDRESS.toLowerCase());
  assert.equal(result.document.policy.selector, "0x36736d1e");
  assert.equal(result.policyHash.length, 66);
  assert.equal(Object.hasOwn(result.document, "policyUri"), false);
});

test("policy metadata document can be regenerated with disabled ENS status for revocation", async () => {
  const { buildAgentPolicyDocument } = await import("../apps/web/lib/policyMetadata.ts");

  const result = buildAgentPolicyDocument(policyInput({ status: "disabled" }));

  assert.equal(result.document.agent.status, "disabled");
  assert.equal(result.document.agent.name, "assistant.agentpassports.eth");
  assert.equal(result.policyHash.length, 66);
});

test("policy metadata hash is stable for the same executable policy", async () => {
  const { buildAgentPolicyDocument } = await import("../apps/web/lib/policyMetadata.ts");

  const first = buildAgentPolicyDocument(policyInput({ capabilities: ["sponsored-execution", "task-log"] }));
  const second = buildAgentPolicyDocument(policyInput({ capabilities: ["task-log", "sponsored-execution"] }));

  assert.equal(first.policyHash, second.policyHash);
});

test("policy metadata document can include Uniswap swap policy for Swapper agents", async () => {
  const { buildAgentPolicyDocument } = await import("../apps/web/lib/policyMetadata.ts");

  const result = buildAgentPolicyDocument(policyInput({
    capabilities: ["task-log", "sponsored-execution", "uniswap-swap"],
    swapPolicy: {
      allowedChainId: 1n,
      allowedTokensIn: ["0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"],
      allowedTokensOut: ["0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"],
      deadlineSeconds: 60n,
      enabled: true,
      maxAmountInWei: 10000000n,
      maxSlippageBps: 50n,
      recipient: AGENT_ADDRESS,
      router: UNISWAP_ROUTER,
      selector: UNISWAP_SELECTOR,
    },
  }));

  assert.equal(result.document.swapPolicy.schema, "agentpassport.swapPolicy.v2");
  assert.equal(result.document.policy.target, UNISWAP_ROUTER);
  assert.equal(result.document.policy.selector, UNISWAP_SELECTOR);
  assert.equal(result.document.swapPolicy.allowedChainId, "1");
  assert.equal(result.document.swapPolicy.maxSlippageBps, "50");
  assert.deepEqual(result.document.agent.capabilities, ["sponsored-execution", "task-log", "uniswap-swap"]);
});

test("policy metadata rejects Uniswap capability without a valid swap policy", async () => {
  const { buildAgentPolicyDocument } = await import("../apps/web/lib/policyMetadata.ts");

  assert.throws(
    () => buildAgentPolicyDocument(policyInput({ capabilities: ["task-log", "sponsored-execution", "uniswap-swap"] })),
    /swapPolicy is required/,
  );
});

test("Pinata upload uses server-only credentials and returns an IPFS policy URI", async () => {
  const { buildAgentPolicyDocument, uploadPolicyDocumentToPinata } = await import("../apps/web/lib/policyMetadata.ts");
  const calls = [];
  const policy = buildAgentPolicyDocument(policyInput());

  const result = await uploadPolicyDocumentToPinata({
    document: policy.document,
    env: { PINATA_JWT: "server-jwt" },
    fetch: async (url, init) => {
      calls.push({ init, url });
      return Response.json({ IpfsHash: "bafyagentpolicy" });
    },
  });

  assert.equal(result.uri, "ipfs://bafyagentpolicy");
  assert.equal(calls[0].url, "https://api.pinata.cloud/pinning/pinJSONToIPFS");
  assert.equal(calls[0].init.headers.authorization, "Bearer server-jwt");
  assert.equal(JSON.parse(calls[0].init.body).pinataContent.agent.name, "assistant.agentpassports.eth");
});

test("Pinata upload fails before network access when server credentials are missing", async () => {
  const { buildAgentPolicyDocument, uploadPolicyDocumentToPinata } = await import("../apps/web/lib/policyMetadata.ts");
  const policy = buildAgentPolicyDocument(policyInput());

  await assert.rejects(
    uploadPolicyDocumentToPinata({
      document: policy.document,
      env: {},
      fetch: async () => {
        throw new Error("fetch should not be called");
      },
    }),
    /PINATA_JWT or PINATA_API_KEY and PINATA_SECRET_API_KEY are required/,
  );
});

test("Pinata unpin extracts old policy CIDs and calls the unpin endpoint", async () => {
  const { extractPinataCidFromUri, unpinPolicyDocumentFromPinata } = await import("../apps/web/lib/policyMetadata.ts");
  const calls = [];

  assert.equal(extractPinataCidFromUri("ipfs://bafyoldpolicy"), "bafyoldpolicy");
  assert.equal(extractPinataCidFromUri("https://gateway.pinata.cloud/ipfs/bafyoldpolicy"), "bafyoldpolicy");
  assert.equal(extractPinataCidFromUri("https://example.com/not-ipfs/bafyoldpolicy"), null);

  const result = await unpinPolicyDocumentFromPinata({
    env: { PINATA_JWT: "server-jwt" },
    fetch: async (url, init) => {
      calls.push({ init, url });
      return new Response(null, { status: 200 });
    },
    policyUri: "ipfs://bafyoldpolicy",
  });

  assert.deepEqual(result, { cid: "bafyoldpolicy", status: "unpinned" });
  assert.equal(calls[0].url, "https://api.pinata.cloud/pinning/unpin/bafyoldpolicy");
  assert.equal(calls[0].init.method, "DELETE");
  assert.equal(calls[0].init.headers.authorization, "Bearer server-jwt");
});

test("Pinata unpin skips blank or non-IPFS policy URIs", async () => {
  const { unpinPolicyDocumentFromPinata } = await import("../apps/web/lib/policyMetadata.ts");
  const fetcher = async () => {
    throw new Error("fetch should not be called");
  };

  assert.deepEqual(
    await unpinPolicyDocumentFromPinata({
      env: { PINATA_JWT: "server-jwt" },
      fetch: fetcher,
      policyUri: "",
    }),
    { cid: null, status: "skipped" },
  );

  assert.deepEqual(
    await unpinPolicyDocumentFromPinata({
      env: { PINATA_JWT: "server-jwt" },
      fetch: fetcher,
      policyUri: "https://example.com/not-ipfs/bafyoldpolicy",
    }),
    { cid: null, status: "skipped" },
  );
});
